AllCops:
  TargetRubyVersion: 2.4
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - 'tasks/*'
    - 'spec/**/*'
    - 'obs_github_deployments.gemspec'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120
